modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/right-click-harvest/issues"

[[mods]]
modId = "rightclickharvest"
version = "${version}"
displayName = "Right Click Harvest"
displayURL = "https://github.com/JamCoreModding/right-click-harvest"
logoFile = "icon.png"
authors = "Jamalam"
description = "Right click crops to harvest them - with style."

[[dependencies.rightclickharvest]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "rightclickharvest.mixins.json"
